### ISSUE TITLE
Errors Gloss

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Mortar#1]
```
WARN 09/03/2019 02:41:50
02:41:50[Mortar]: Plugin Mortar v1.0.17 generated an exception while executing task 5010
Console 09/03/2019 02:41:50
02:41:50com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 45 path $.text
at com.google.gson.internal.Streams.parse(Streams.java:60) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[patched_1.13.2.jar:git-Paper-535]
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497) ~[patched_1.13.2.jar:git-Paper-535]
at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522) ~[patched_1.13.2.jar:git-Paper-535]
at net.minecraft.server.v1_13_R2.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:404) ~[patched_1.13.2.jar:git-Paper-535]
at mortar.api.nms.Catalyst13.s(Catalyst13.java:580) ~[?:?]
at mortar.api.nms.Catalyst13.getMetaEntityCustomName(Catalyst13.java:831) ~[?:?]
at com.volmit.gloss.display.GlossDisplayComponent.sendName(GlossDisplayComponent.java:261) ~[?:?]
at com.volmit.gloss.display.GlossDisplayComponent.update(GlossDisplayComponent.java:81) ~[?:?]
at com.volmit.gloss.display.GlossDisplay.lambda$0(GlossDisplay.java:157) ~[?:?]
at mortar.api.sched.J$2.run(J.java:244) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-535]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-535]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-535]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 45 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.Streams.parse(Streams.java:48) ~[patched_1.13.2.jar:git-Paper-535]
... 16 more
02:41:51 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-535]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-535]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 36 path $.text
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[patched_1.13.2.jar:git-Paper-535]
at com.google.gson.internal.Streams.parse(Streams.java:48) ~[patched_1.13.2.jar:git-Paper-535]
... 16 more
```
paperspigot 1.13.2 build 535 gloss 1.0.14

Wasnt too sure where to post this.

**Comment by cyberpwnn** [comment]
Not sure what this is.

**Comment by DavidRockin** [comment]
Are you still having this issue? Can you send the config files or methods to reproduce. There's a chance something went wrong with GSON and didn't terminate a quote or unicode character.

**Comment by DavidRockin** [comment]
Closing this due to inactivity.
