### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/Mortar#10]
**Describe the bug**
Mortar throws this error on startup.
```
>.... [16:24:07 WARN]: [Mortar] Plugin Mortar v1.0.71 generated an exception while executing task 77
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at mortar.lang.collection.GList.<init>(GList.java:106) ~[?:?]
at mortar.lang.collection.GMap.k(GMap.java:122) ~[?:?]
at com.volmit.gloss.controllers.HotloadController.tick(HotloadController.java:53) ~[?:?]
at com.volmit.gloss.controllers.HotloadController.lambda$start$0(HotloadController.java:19) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-167]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-167]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-167]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**To Reproduce**
1. Start up the server

**Expected behavior**
No error should appear

**Server and Plugin Informations**
- Installed plugins:
  - AdvancedCustomItemAPI
  - AdvancedCustomMenu
  - AdvancedModreq
  - Animatronics*
  - ArmorStandTools
  - BannerBoard*
  - BKCommonLib
  - BlockParty
  - DeluxeChat
  - DeluxePlugins*
  - DiscordSRV
  - Essentials
  - EssentialsSpawn
  - Gloss*
  - HeadDatabase*
  - HelpPagePlus
  - InfoHeads
  - ItemsAdder
  - LightAPI*
  - LuckPerms
  - Maplands
  - MessageAnnouncer
  - MiniaturePets*
  - Mortar*
  - PlaceholderAPI*
  - ProtocolLib*
  - QuickShop
  - ReWorld
  - ServerListPlus
  - SurveyPlus*
  - Vault
  - WarpSystem
  - WorldEdit
  - WorldGuard
- Mortar Version:
  - Mortar: 1.0.71
- Server Platform and Version [eg: PaperSpigot 1.14.4]:
  - PaperMC 163 (1.14.4)
- Operating System (if applicable):
  - Not available

**Files**:
[Mortar.zip](https://github.com/VolmitSoftware/Mortar/files/3510022/Mortar.zip)

**Comment by DavidRockin** [comment]
Added some null checks for Mortar 1.0.72 in 2856dba9e2de0c6d9f237701f9b5208ed3cafa1d
