### ISSUE TITLE
NullPointerException on teleport

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/Mortar#11]
I receive this error when I teleport from one world to another, where the target world has holograms from Gloss.
```
>.... [09:33:13 WARN]: java.lang.NullPointerException
>.... [09:33:13 WARN]: at java.util.TreeMap.rotateLeft(TreeMap.java:2224)
>.... [09:33:13 WARN]: at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2291)
>.... [09:33:13 WARN]: at java.util.TreeMap.put(TreeMap.java:582)
>.... [09:33:13 WARN]: at mortar.util.reflection.Violator.p(Violator.java:73)
>.... [09:33:13 WARN]: at mortar.util.reflection.Violator.getDeclaredField(Violator.java:136)
>.... [09:33:13 WARN]: at mortar.util.reflection.V.set(V.java:140)
>.... [09:33:13 WARN]: at mortar.api.nms.Catalyst14.teleportEntity(Catalyst14.java:569)
>.... [09:33:13 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendTeleport(GlossDisplayComponent.java:299)
>.... [09:33:13 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendMove(GlossDisplayComponent.java:305)
>.... [09:33:13 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.update(GlossDisplayComponent.java:133)
>.... [09:33:13 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.update(GlossDisplayComponent.java:224)
>.... [09:33:13 WARN]: at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:180)
>.... [09:33:13 WARN]: at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
>.... [09:33:13 WARN]: at com.volmit.gloss.context.GlossContextualView.lambda$update$4(GlossContextualView.java:232)
>.... [09:33:13 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
>.... [09:33:13 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>.... [09:33:13 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>.... [09:33:13 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>.... [09:33:13 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by DavidRockin** [comment]
Looks like TreeMaps aren't thread safe, going to see if using a concurrent skiplist will resolve this? 5861615a53f61f3c60b988e1f35130b3531a1462

**Comment by DavidRockin** [comment]
Closing this issue for Mortar 1.0.72, if this issue occurs again please reopen it.
