### ISSUE TITLE
Error when disabling

### ISSUE THREAD

**Issue by HSGamer** [VolmitSoftware/Mortar#2]
```
[11:20:22] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:20:22] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:20:22] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:20:22] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:20:22] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:507)
[11:20:22] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:558)
[11:20:22] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:20:22] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:425)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418)
[11:20:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:20:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651)
[11:20:22] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873)
[11:20:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:20:22] [Server thread/ERROR]: Error occurred while disabling Mortar v1.0.17 (Is it up to date?)
java.lang.NullPointerException: null
	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:509) ~[?:?]
	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:558) ~[?:?]
	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90) ~[?:?]
	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:425) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:651) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:873) ~[patched_1.13.2.jar:git-Paper-561]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
Latest Mortar. PaperSpigot 1.13.2

**Comment by cyberpwnn** [comment]
Update
