### ISSUE TITLE
Particle failed to initialize

### ISSUE THREAD

**Issue by HSGamer** [VolmitSoftware/Mortar#3]
```
[19:42:51] [Craft Scheduler Thread - 70/WARN]: [Mortar] Plugin Mortar v1.0.21 generated an exception while executing task 35943
mortar.api.particle.ParticleEffect$ParticlePacket$PacketInstantiationException: Packet instantiation failed
	at mortar.api.particle.ParticleEffect$ParticlePacket.initializePacket(ParticleEffect.java:1933) ~[?:?]
	at mortar.api.particle.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:1952) ~[?:?]
	at mortar.api.particle.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:1982) ~[?:?]
	at mortar.api.particle.ParticleEffect.display(ParticleEffect.java:942) ~[?:?]
	at mortar.api.particle.ParticleEffect.display(ParticleEffect.java:964) ~[?:?]
	at com.volmit.gloss.command.CommandMoveHologram.hit(CommandMoveHologram.java:147) ~[?:?]
	at com.volmit.gloss.command.CommandMoveHologram$1.run(CommandMoveHologram.java:121) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[akarin.jar:git-Akarin-"4c4d318"]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[akarin.jar:git-Akarin-"4c4d318"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[akarin.jar:git-Akarin-"4c4d318"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at mortar.api.particle.ParticleEffect$ParticlePacket.initializePacket(ParticleEffect.java:1902) ~[?:?]
	... 12 more
```
Paperspigot 1.13.2 latest, Gloss 1.0.18, Latest Mortar

**Comment by cyberpwnn** [comment]
Fixed. btw its mortar 1.0.40 now (update)
