### ISSUE TITLE
Iron axe error

### ISSUE THREAD

**Issue by Florianpal1** [VolmitSoftware/Mortar#4]
```   [12:09:03 ERROR]: Could not pass event PlayerInteractEvent to Mortar v1.0.46
java.lang.NoSuchFieldError: org/bukkit/Sound.ENTITY_ENDEREYE_DEATH
at mortar.api.scm.SCMController.on(SCMController.java:216) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-620]
at org.bukkit.plugin.EventExecutor$$Lambda$1742.00000000B4BF34B0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-620]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-620]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-620]
 ```

PaperSpigot : git-Paper-620
Mortar : 1.0.46
Gloss : 1.0.28
This error occur when I use iron axe.

**Comment by DavidRockin** [comment]
1.13.x had a huge refactor for all sound enums, would need to implement a compatibility layer if not implemented yet. 

If you are still experiencing this issue, do you receive an IndexOutOfBoundsException, see issue #7. Will deploy a patch in a few days.
