### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/Mortar#5]
```
WARN 23/05/2019 07:51:30
07:51:30 at mortar.util.reflection.V.set(V.java:140)
at mortar.api.nms.Catalyst13.spawnArmorStand(Catalyst13.java:634)
at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:349)
at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:235)
at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:159)
at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
at com.volmit.gloss.context.GlossContextualView.lambda$4(GlossContextualView.java:228)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.NullPointerException
at mortar.util.reflection.V.set(V.java:140)
at mortar.api.nms.Catalyst13.spawnArmorStand(Catalyst13.java:636)
at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:349)
at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:235)
at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:159)
at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
at com.volmit.gloss.context.GlossContextualView.lambda$4(GlossContextualView.java:228)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.NullPointerException
at mortar.util.reflection.V.set(V.java:140)
at mortar.api.nms.Catalyst13.spawnArmorStand(Catalyst13.java:636)
at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:349)
at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:235)
at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:159)
at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
at com.volmit.gloss.context.GlossContextualView.lambda$4(GlossContextualView.java:228)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by DavidRockin** [comment]
Confirmed in 1.12. Not sure what happens, somehow the same object just gets null? :confused: 

```
 [22:32:17 WARN]: java.lang.NullPointerException
[22:32:17 WARN]: at mortar.util.reflection.V.set(V.java:140)
[22:32:17 WARN]: at mortar.api.nms.Catalyst12.spawnArmorStand(Catalyst12.java:585)
[22:32:17 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:350)
[22:32:17 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:238)
[22:32:17 WARN]: at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:159)
[22:32:17 WARN]: at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
[22:32:17 WARN]: at com.volmit.gloss.context.GlossContextualView.lambda$update$4(GlossContextualView.java:228)
[22:32:17 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[22:32:17 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[22:32:17 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[22:32:17 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[22:32:17 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Andre601** [comment]
Also got this on 1.14.4 on after I joined:
```
>.... [17:06:42 INFO]: UUID of player Andre_601 is 286f8d0c-b571-4720-b7ab-f2929cb38120
>.... [17:06:44 WARN]: java.lang.NullPointerException
>.... [17:06:44 WARN]: at mortar.util.reflection.V.set(V.java:140)
>.... [17:06:44 WARN]: at mortar.api.nms.Catalyst14.spawnArmorStand(Catalyst14.java:587)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:328)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:210)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:165)
>.... [17:06:44 WARN]: at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
>.... [17:06:44 WARN]: at com.volmit.gloss.context.GlossContextualView.lambda$update$4(GlossContextualView.java:228)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>.... [17:06:44 WARN]: java.lang.NullPointerException
>.... [17:06:44 WARN]: at mortar.util.reflection.V.set(V.java:140)
>.... [17:06:44 WARN]: at mortar.api.nms.Catalyst14.spawnArmorStand(Catalyst14.java:588)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.sendSpawn(GlossDisplayComponent.java:328)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplayComponent.create(GlossDisplayComponent.java:210)
>.... [17:06:44 WARN]: at com.volmit.gloss.display.GlossDisplay.update(GlossDisplay.java:165)
>.... [17:06:44 WARN]: at com.volmit.gloss.context.GlossStaticContext.update(GlossStaticContext.java:98)
>.... [17:06:44 WARN]: at com.volmit.gloss.context.GlossContextualView.lambda$update$4(GlossContextualView.java:228)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>.... [17:06:44 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by DavidRockin** [comment]
Possibly related to #11  ?

**Comment by DavidRockin** [comment]
Closing this issue for Mortar 1.0.72, if this issue occurs again please reopen it.
