### ISSUE TITLE
Error on Shutdown (1.13.2 Paper)

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Mortar#8]
[11:24:24] [Server thread/INFO]: |INFO| Mortar NMP Packet Listener Closed
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:24:24] [Server thread/WARN]: java.lang.NoSuchFieldException: knownCommands
[11:24:24] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.Violator.getDeclaredField(Violator.java:123)
[11:24:24] [Server thread/WARN]: 	at mortar.util.reflection.V.get(V.java:97)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommand(MortarPlugin.java:515)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterCommands(MortarPlugin.java:574)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.unregisterAll(MortarPlugin.java:90)
[11:24:24] [Server thread/WARN]: 	at mortar.bukkit.plugin.MortarPlugin.onDisable(MortarPlugin.java:293)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[11:24:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:377)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:652)
[11:24:24] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:874)
[11:24:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by DavidRockin** [comment]
Issue occurred when the reflection library failed to fetch the fields for Bukkit's CommandMap. 1.13 they extended the CommandMap to implement an API layer for it. It has been resolved in Mortar 1.0.70 and will ship in a few days.
